lint modify

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -4,6 +4,7 @@ on:
   pull_request:
     branches:
       - master
+
 jobs:
   lint:
     runs-on: ubuntu-latest
@@ -19,8 +20,8 @@ jobs:
       - name: Install dependencies
         run: pip install black flake8
 
-      - name: Run Black
-        run: black --check .
+      - name: Run Black (Fail on unformatted code)
+        run: black --check .  # This step will FAIL if code needs formatting
 
-      - name: Run Flake8
-        run: flake8 .
+      - name: Run Flake8 (Lint but do NOT fail)
+        run: flake8 . || true  # "|| true" ensures this step never fails
